version: '3'
services:
    web:
        container_name: docker-vue
        restart: always
        build: ./client
        volumes:
            - './client:/usr/src/api'
        ports:
            - '80:8080'
        links:
            - api
    api:
        container_name: docker-sails
        restart: always
        build: './server'
        volumes:
            - './server:/usr/src/app'
        ports:
            - '8080:80'
        links:
            - db
    db:
        container_name: mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        # volumes:
        #     - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sails-test
        ports:
            - "3306:3306"